"""empty message

Revision ID: 87d705b94db8
Revises: 
Create Date: 2022-12-27 11:26:16.917798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87d705b94db8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('folder_name', sa.String(length=50), nullable=True),
    sa.Column('storagesize', sa.String(length=20), nullable=True),
    sa.Column('auth', sa.String(length=50), nullable=True),
    sa.Column('permlevel', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('maximages', sa.Integer(), nullable=True),
    sa.Column('themecolor', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    op.drop_table('admins')
    # ### end Alembic commands ###
